#!/usr/bin/env python

import click

from googletrans import Translator
from utils.star_class_map import spectral_class_map, oddity_map
from utils.portmanfaux import PortManFaux


@click.group()
def main():
    """
    It's a start!
    """


@click.command()
@click.argument('word')
def translate(word):
    trans = Translator()
    icelandic = trans.translate(word, dest='is').text
    click.echo(f'{word} -> {icelandic}')


@click.command()
@click.argument('spectral_class')
def name_star(spectral_class):
    chopped_string = list(spectral_class)

    spectral_class = chopped_string[0]
    brightness = int(chopped_string[1]) // 2
    oddities = []

    if len(chopped_string) > 2:
        oddities = [oddity_map[oddity.upper()] for oddity in chopped_string[2:]]

    click.echo([spectral_class_map[spectral_class][brightness], oddities])


@click.command()
@click.option('--num-words', '-n', help='Number of words to generate')
@click.argument('input_words')
def portmanfaux(num_words, input_words):
    click.echo(input_words)
    word_gen = PortManFaux(input_words=input_words)
    click.echo(word_gen.get_prospects(number=int(num_words)))


if __name__ == '__main__':
    main.add_command(translate)
    main.add_command(name_star)
    main.add_command(portmanfaux)
    main()
